import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import { applyStreamEvent, LiveResourceStore, SSEDecoder } from "../src/index.ts";
import { body } from "./conformance.ts";

for (const scenario of [
  { fixture: "final-bookkeeping-only", upstream: "cm-app.v2-bookkeeping", heldRV: "1001", finalRV: "1002" },
  { fixture: "status-only-churn", upstream: "deploy-web.v2", heldRV: "3001", finalRV: "3002" },
]) {
  test(`${scenario.fixture}: final visible content converges with an older held RV`, () => {
    // These bytes are generated by the real gateway after the entire watch script is consumed.
    // There is no later visible write or resnapshot to hide an incorrect final-state invariant.
    const bytes = readFileSync(
      new URL(`../../../conformance/gen/sse/${scenario.fixture}.sse`, import.meta.url),
      "utf8",
    );
    const events = new SSEDecoder().push(bytes);
    assert.deepEqual(
      events.map((event) => event.type),
      ["reset", "added", "synced"],
    );
    const store = new LiveResourceStore();
    for (const event of events) applyStreamEvent(store, event);

    const upstream = body(scenario.upstream);
    const uid = upstream.metadata.uid;
    const held = structuredClone(store.server(uid));
    assert.equal(held.metadata.resourceVersion, scenario.heldRV);
    assert.equal(upstream.metadata.resourceVersion, scenario.finalRV);
    assert.notEqual(held.metadata.resourceVersion, upstream.metadata.resourceVersion);
    assert.deepEqual(store.redactions(uid), []);
    assert.deepEqual(events[1]!.redacted, []);

    // Spell out the declared projection independently of the gateway's suppression digest.
    delete upstream.metadata.managedFields;
    const annotations = upstream.metadata.annotations as Record<string, unknown> | undefined;
    if (annotations) delete annotations["kubectl.kubernetes.io/last-applied-configuration"];
    if (scenario.fixture === "status-only-churn") delete upstream.status;
    delete upstream.metadata.resourceVersion;
    delete held.metadata.resourceVersion;
    assert.deepEqual(held, upstream);
  });
}
